# 서버포트
server:
  port: 8090

app:
  server:
    type: AUTH_SERVER
    id: auth-server-1

spring:
  # 데이터베이스 설정
  datasource:
#    url: jdbc:postgresql://localhost:5432/grpc
#    username: root
#    password: 1234
#    driver-class-name: org.postgresql.Driver
    url: jdbc:log4jdbc:mysql://localhost:3306/grpc?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: scott
    password: tiger
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-test-query: SELECT 1
  # JPA 설정
  jpa:
#    database: POSTGRESQL
    database: MYSQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

# gRPC 서버포트
grpc:
  server:
    port: 50051 # gRPC 서버 포트
    maxInboundMessageSize: 10485760 # 최대 메시지 크기 (10MB)
    security:
      enabled: false

jwt:
  secret-key: "your-256-bit-secret-key-base64-encoded"